# Generated by Django 5.1.4 on 2024-12-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sales_Bot", "0002_preference_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="user",
        ),
    ]
