# Generated by Django 5.1.4 on 2024-12-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales_Bot", "0003_remove_preference_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.CharField(max_length=1000)),
            ],
        ),
    ]
