# Generated by Django 5.1.4 on 2025-01-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales_Bot", "0005_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_input",
            name="llm_response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
