# Generated by Django 5.1.4 on 2025-01-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sales_Bot", "0006_user_input_llm_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user_input",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
